### ISSUE TITLE
Create invoice template in docx format

### ISSUE THREAD

**Issue by paragasu** [phisoft/phidental-web#13]
Create invoice standard format using openoffice and save in docx format. Must contain,
- [x] Logo
- [x] Address & contact number
- [x] Service list ( use table, add dummy ) - No, description, Amount
- [x] Date
- [x] Invoice number 
- [x] Total amount

**Comment by oliverkelvin96** [comment]
[phidental-invoice.docx](https://github.com/phisoft/phidental-web/files/2913194/phidental-invoice.docx)
