### ISSUE TITLE
Create bill template in docx format

### ISSUE THREAD

**Issue by paragasu** [phisoft/phidental-web#14]
Bill is issued after payment is received.
Create bill standard format using openoffice writer and save in docx format. Must contain,
- [x] Logo
- [x] Address & contact number
- [x] Payment method
- [x] Service list ( use table, add dummy ) - No, description, Amount
- [x] Date
- [x] Invoice number 
- [x] Total amount

**Comment by oliverkelvin96** [comment]
[phidental-BILL.docx](https://github.com/phisoft/phidental-web/files/2913193/phidental-BILL.docx)
