### ISSUE TITLE
Generate bill following the template using jspdf

### ISSUE THREAD

**Issue by paragasu** [phisoft/phidental-web#17]
Generate pdf like this template in pdf. Can use codepen,

[phidental-BILL.docx](https://github.com/phisoft/phidental-web/files/3088097/phidental-BILL.docx)

Reference
https://www.npmjs.com/package/jspdf

**Comment by kennethrick96** [comment]
[generate-pdf.zip](https://github.com/phisoft/phidental-web/files/3115956/generate-pdf.zip)

**Comment by paragasu** [comment]
Use autotable plugin to display table https://github.com/simonbengtsson/jsPDF-AutoTable

**Comment by paragasu** [comment]
-  [ ] Add date
-  [ ] Add amount
