### ISSUE TITLE
Update floor plan layout

### ISSUE THREAD

**Issue by paragasu** [phisoft/phidental-web#18]
[KP Phi Floor Plan 1.2.pdf](https://github.com/phisoft/phidental-web/files/4855194/KP.Phi.Floor.Plan.1.2.pdf)

- [x] Rename future sugery 2 -> Utility Room
- [x] Move freezer to Utility top right corner
- [x] Erase Janitor Room

**Comment by izahshahirah** [comment]
[KP.Phi.Floor.Plan.1.2-updated.pdf](https://github.com/phisoft/phidental-web/files/4855307/KP.Phi.Floor.Plan.1.2-updated.pdf)
