### ISSUE TITLE
Fix blank images after update

### ISSUE THREAD

**Issue by paragasu** [phisoft/phidental-web#22]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/27353/104615669-6ac7f480-56c4-11eb-937e-fc53b5dee14f.png">

**Comment by izahshahirah** [comment]
@paragasu , dekat saya okay

![Screenshot-2021-01-15-at-12 01 27-PM](https://user-images.githubusercontent.com/60636305/104679976-ca0c2000-5729-11eb-9c19-765b6f35ed14.jpg)
