### ISSUE TITLE
Fix favicon 

### ISSUE THREAD

**Issue by paragasu** [phisoft/phidental-web#25]
Make the favicon background transparent / remove ugly white bg

<img width="287" alt="image" src="https://user-images.githubusercontent.com/27353/169941605-64526514-0bd2-4c89-8b47-026ddeedb539.png">

**Comment by niwle** [comment]
After removing the white background

![Screenshot 2022-05-24 135834](https://user-images.githubusercontent.com/61690172/169960211-9642f68f-5ac2-4153-ab31-b62b8955c33a.png)
